version: '3'
services:
  rdb:
    image: mariadb
    restart: always
    volumes: 
      - /srv/radius/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pain0fRoot
      MYSQL_DATABASE: freeradius
      MYSQL_USER: freeradius
      MYSQL_PASSWORD: radius5trongPa55
  radiusproc:
    build: ./radius
    depends_on:
      - rdb
    links:
     - "rdb:mysql"
    restart: always
    ports:
     - "1812:1812/udp"
     - "1813:1813/udp"
#    volumes: 
#      - /srv/rsyst:/var/log
    environment:
      - TZ=Europe/Moscow
      - RADIUS_LISTEN_IP=* 
      - RADIUS_CLIENTS=secret@192.168.200.88
      - RADIUS_SQL=true 
      - RADIUS_DB_HOST=mysql 
      - RADIUS_DB_NAME=freeradius 
      - RADIUS_DB_USERNAME=freeradius 
      - RADIUS_DB_PASSWORD=radius5trongPa55 
#  web:
#    image: instrutordocker/dexter-loganalyzer-banco
#    restart: always
#    ports:
#      - 888:8080
#    volumes: 
#      - /srv/logan/log:/mnt/log/
#      - /srv/logan/http:/var/www/html/