version: '3'
services:
  db:
    image: mariadb
    restart: always
    volumes: 
      - /srv/rsql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: super2man2
  rsyslogm:
    build: ./rcl
    restart: always
    ports:
     - "515:514/udp"
    volumes: 
      - /srv/rsyst:/var/log
    environment:
      - TZ=Europe/Moscow
  loganalyzer:
    image: instrutordocker/dexter-loganalyzer-banco
    restart: always
    ports:
      - 188:8080
    volumes: 
      - /srv/logan/log:/mnt/log/
      - /srv/logan/http:/var/www/html/